name: LeetCode Daily Question

on:
  schedule:
    - cron: '0 20 * * *'  # UTC 20:00 Every day, which is 04:00 Beijing time next day
  workflow_dispatch:

jobs:
  leetcode_daily_question:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Fetch Question
        id: fetch_question
        run: |
          python fetch_question.py

      - name: Generate PDF
        run: |
          python generate_pdf.py

      - name: Send Email
        run: |
          python send_email.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          KINDLE_EMAIL: ${{ secrets.KINDLE_EMAIL }}


