name: LeetCode Daily Question

on:
  schedule:
    - cron: '0 20 * * *'  # UTC 20:00 Every day, which is 04:00 Beijing time next day
  workflow_dispatch:

jobs:
  leetcode_daily_question:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Cache wkthtmltopdf
        uses: actions/cache@v2
        id: cache-wkhtmltopdf
        with:
          path: "~/wkhtmltox/"
          key: ${{ runner.os }}-wkhtmltopdf-${{ hashFiles('**/*.deb') }}

      - name: Download wkthtmltopdf & dependencies
        if: steps.cache-wkhtmltopdf.outputs.cache-hit != 'true'
        run: |
          mkdir ~/wkhtmltox
          wget -O ~/wkhtmltox/wkhtmltox.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
          wget -O ~/wkhtmltox/xfonts-encodings.deb http://archive.ubuntu.com/ubuntu/pool/main/x/xfonts-encodings/xfonts-encodings_1.0.4-2_all.deb
          wget -O ~/wkhtmltox/xfonts-utils.deb http://archive.ubuntu.com/ubuntu/pool/main/x/xfonts-utils/xfonts-utils_7.7+6_amd64.deb
          wget -O ~/wkhtmltox/xfonts-75dpi.deb http://archive.ubuntu.com/ubuntu/pool/universe/x/xfonts-75dpi/xfonts-75dpi_1.0.4+nmu1_all.deb
          wget -O ~/wkhtmltox/xfonts-base.deb http://archive.ubuntu.com/ubuntu/pool/main/x/xfonts-base/xfonts-base_1.0.4+nmu1_all.deb

      - name: Install wkhtmltopdf
        run: |
          sudo dpkg -i ~/wkhtmltox/xfonts-encodings.deb
          sudo dpkg -i ~/wkhtmltox/xfonts-utils.deb
          sudo dpkg -i ~/wkhtmltox/xfonts-75dpi.deb
          sudo dpkg -i ~/wkhtmltox/xfonts-base.deb
          sudo dpkg -i ~/wkhtmltox/wkhtmltox.deb

      - name: Fetch Question
        id: fetch_question
        run: |
          python fetch_question.py

      - name: Generate PDF
        run: |
          python generate_pdf.py

      - name: Send Email
        run: |
          python send_email.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          KINDLE_EMAIL: ${{ secrets.KINDLE_EMAIL }}


